set BUILD_TYPE=%1
IF "%BUILD_TYPE%"=="" set BUILD_TYPE=Release

set TLRENDER_NET=OFF
set TLRENDER_OCIO=ON
set TLRENDER_FFMPEG=ON
set TLRENDER_FFMPEG_MINIMAL=OFF
set TLRENDER_USD=ON
set TLRENDER_BMD=ON
set TLRENDER_BMD_SDK="C:\Dev\BMD\Blackmagic DeckLink SDK 12.7"
set FEATHER_TK_API=GL_4_1

DJV\etc\Windows\windows-build-gha.bat %BUILD_TYPE%
