include(ExternalProject)

set(OPENVDB_CORE_SHARED ON)
set(OPENVDB_CORE_STATIC OFF)
if(NOT BUILD_SHARED_LIBS)
    set(OPENVDB_CORE_SHARED OFF)
    set(OPENVDB_CORE_STATIC ON)
endif()

set(OpenVDB_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_INSTALL_LIBDIR=lib
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DOPENVDB_CORE_SHARED=${OPENVDB_CORE_SHARED}
    -DOPENVDB_CORE_STATIC=${OPENVDB_CORE_STATIC})
if(CMAKE_CXX_STANDARD)
    set(OpenVDB_ARGS ${OpenVDB_ARGS} -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD})
endif()

ExternalProject_Add(
    OpenVDB
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OpenVDB
    DEPENDS OpenEXR IlmBase Boost TBB Blosc
    GIT_REPOSITORY https://github.com/AcademySoftwareFoundation/openvdb.git
    GIT_TAG v7.1.0
    CMAKE_ARGS ${OpenVDB_ARGS})
