include(ExternalProject)

ExternalProject_Add(
    MbedTLS
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/MbedTLS
    DEPENDS ZLIB
    URL https://github.com/ARMmbed/mbedtls/archive/v2.24.0.tar.gz
    CMAKE_ARGS
        -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
        -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
        -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
        -DCMAKE_FIND_FRAMEWORK=${CMAKE_FIND_FRAMEWORK}
        -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
        -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
        -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
        -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS})

