include(ExternalProject)

set(TLRENDER_GIT_REPOSITORY "https://github.com/darbyjohnston/tlRender.git")
set(TLRENDER_GIT_TAG "d74dc723fbac245e92e67441d63d16a2319ad091")

set(TLRENDER_DEPS)
set(TLRENDER_ARGS
    -DTLRENDER_NET=${TLRENDER_NET}
    -DTLRENDER_OCIO=${TLRENDER_OCIO}
    -DTLRENDER_FFMPEG=${TLRENDER_FFMPEG}
    -DTLRENDER_FFMPEG_MINIMAL=${TLRENDER_FFMPEG_MINIMAL}
    -DTLRENDER_USD=${TLRENDER_USD}
    -DTLRENDER_USD_PYTHON=${TLRENDER_USD_PYTHON}
    -DTLRENDER_BMD=${TLRENDER_BMD}
    -DTLRENDER_BMD_SDK=${TLRENDER_BMD_SDK}
    -DTLRENDER_PROGRAMS=OFF
    -DTLRENDER_EXAMPLES=OFF
    -DTLRENDER_TESTS=OFF
    -Dfeather_tk_API=${feather_tk_API}
    ${DJV_EXTERNAL_ARGS})

ExternalProject_Add(
    tlRender
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/tlRender
    DEPENDS ${TLRENDER_DEPS}
    GIT_REPOSITORY ${TLRENDER_GIT_REPOSITORY}
    GIT_TAG ${TLRENDER_GIT_TAG}
    INSTALL_COMMAND ""
    SOURCE_SUBDIR etc/SuperBuild
    LIST_SEPARATOR |
    CMAKE_ARGS ${TLRENDER_ARGS})
