include(ExternalProject)

set(curl_ARGS
	-DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
	-DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
	-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
	-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
	-DBUILD_SHARED_LIBS=${CURL_SHARED_LIBS}
	-DCURL_DISABLE_LDAP=TRUE)
set(curl_DEPENDS ZLIB_EXTERNAL)
if(WIN32)
	set(curl_ARGS ${curl_ARGS} -DCMAKE_USE_WINSSL=TRUE)
elseif (APPLE)
	set(curl_ARGS ${curl_ARGS} -DCMAKE_USE_SECTRANSP=TRUE)
else()
	set(curl_ARGS ${curl_ARGS} -DCMAKE_USE_MBEDTLS=TRUE)
	set(curl_DEPENDS ${curl_DEPENDS} MbedTLS_EXTERNAL)
endif()

ExternalProject_Add(
    curl
	PREFIX ${CMAKE_CURRENT_BINARY_DIR}/curl
    DEPENDS ${curl_DEPENDS}
    URL https://github.com/curl/curl/releases/download/curl-7_65_1/curl-7.65.1.tar.bz2
    CMAKE_ARGS ${curl_ARGS})
