include(ExternalProject)

if(NOT FSeqThirdParty)
	ExternalProject_Add(
		FSeqThirdParty
		PREFIX ${CMAKE_CURRENT_BINARY_DIR}/FSeq
		GIT_REPOSITORY https://github.com/darbyjohnston/FSeq.git
		CMAKE_ARGS
			-DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
			-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
			-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
			-DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
			-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
			-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
			-DBUILD_SHARED_LIBS=${FSeq_SHARED_LIBS})
endif()

set(FSeq_FOUND TRUE)
set(FSeq_INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
if(WIN32)
	set(FSeq_LIBRARY ${CMAKE_INSTALL_PREFIX}/lib/FSeq${CMAKE_STATIC_LIBRARY_SUFFIX})
else()
	set(FSeq_LIBRARY ${CMAKE_INSTALL_PREFIX}/lib/libFSeq${CMAKE_STATIC_LIBRARY_SUFFIX})
endif()

if(FSeq_FOUND AND NOT TARGET FSeq::FSeq)
    add_library(FSeq::FSeq UNKNOWN IMPORTED)
    add_dependencies(FSeq::FSeq FSeqThirdParty)
	set_property(TARGET FSeq::FSeq PROPERTY IMPORTED_LOCATION ${FSeq_LIBRARY})
	set_property(TARGET FSeq::FSeq PROPERTY INTERFACE_LINK_LIBRARIES ${FSeq_LINK_LIBRARIES})
	set_property(TARGET FSeq::FSeq PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${FSeq_INCLUDE_DIRS})
	set_property(TARGET FSeq::FSeq PROPERTY INTERFACE_COMPILE_DEFINITIONS FSeq_FOUND)
endif()
if(FSeq_FOUND AND NOT TARGET FSeq)
    add_library(FSeq INTERFACE)
    target_link_libraries(FSeq INTERFACE FSeq::FSeq)
endif()
