include(ExternalProject)

set(OTIO_ARGS
	-DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
	-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
	-DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
	-DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
	-DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
	-DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
	-DBUILD_SHARED_LIBS=${OTIO_SHARED_LIBS})
set(OTIO_DEPENDS ${OTIO_DEPENDS})
ExternalProject_Add(
    OTIOThirdParty
	PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OTIO
    DEPENDS ${OTIO_DEPENDS}
    GIT_REPOSITORY https://github.com/PixarAnimationStudios/OpenTimelineIO.git
	PATCH_COMMAND
	    ${CMAKE_COMMAND} -E tar xf
	    ${CMAKE_SOURCE_DIR}/third-party/otio-patch.tar.gz
    CMAKE_ARGS ${OTIO_ARGS})

set(OTIO_FOUND TRUE)
set(OTIO_INCLUDE_DIRS ${CMAKE_INSTALL_PREFIX}/include)
if(WIN32)
	set(OTIO_LIBRARY ${CMAKE_INSTALL_PREFIX}/lib/otio${CMAKE_STATIC_LIBRARY_SUFFIX})
else()
	set(OTIO_LIBRARY ${CMAKE_INSTALL_PREFIX}/lib/libotio${CMAKE_STATIC_LIBRARY_SUFFIX})
endif()
set(OTIO_LIBRARIES ${OTIO_LIBRARY})

if(OTIO_FOUND AND NOT TARGET OTIO::OTIO)
    add_library(OTIO::OTIO UNKNOWN IMPORTED)
    add_dependencies(OTIO::OTIO OTIOThirdParty)
	if(WIN32)
		set_property(TARGET OTIO::OTIO PROPERTY IMPORTED_LOCATION ${OTIO_LIBRARY})
		set_property(TARGET OTIO::OTIO PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${OTIO_INCLUDE_DIRS})
		set_property(TARGET OTIO::OTIO PROPERTY INTERFACE_COMPILE_DEFINITIONS OTIO_FOUND)
	elseif(APPLE)
		set_property(TARGET OTIO::OTIO PROPERTY IMPORTED_LOCATION ${OTIO_LIBRARY})
		set_property(TARGET OTIO::OTIO PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${OTIO_INCLUDE_DIRS})
		set_property(TARGET OTIO::OTIO PROPERTY INTERFACE_COMPILE_DEFINITIONS OTIO_FOUND)
	else()
		set_property(TARGET OTIO::OTIO PROPERTY IMPORTED_LOCATION ${OTIO_LIBRARY})
		set_property(TARGET OTIO::OTIO PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${OTIO_INCLUDE_DIRS})
		set_property(TARGET OTIO::OTIO PROPERTY INTERFACE_COMPILE_DEFINITIONS OTIO_FOUND)
	endif()
endif()
if(OTIO_FOUND AND NOT TARGET OTIO)
    add_library(OTIO INTERFACE)
    target_link_libraries(OTIO INTERFACE OTIO::OTIO)
endif()
