include(ExternalProject)

set(OPENEXR_RUNTIME_DIR lib)
if(WIN32)
    set(OPENEXR_RUNTIME_DIR bin)
endif()
set(OpenEXR_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_POLICY_DEFAULT_CMP0091:STRING=NEW
    -DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreaded$<$<CONFIG:Debug>:Debug>DLL
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_CXX_STANDARD=11
    -DOPENEXR_BUILD_SHARED=${OPENEXR_SHARED_LIBS}
    -DILMBASE_PACKAGE_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DILMBASE_SHARED_LIBS=${ILMBASE_SHARED_LIBS}
    -DZLIB_SHARED_LIBS=${ZLIB_SHARED_LIBS}
    -DBUILD_SHARED_LIBS=${OPENEXR_SHARED_LIBS}
    -DBUILD_TESTING=OFF
    -DOPENEXR_BUILD_UTILS=OFF
    -DINSTALL_OPENEXR_DOCS=OFF
    -DRUNTIME_DIR=${OPENEXR_RUNTIME_DIR})
ExternalProject_Add(
    OpenEXR
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OpenEXR
    DEPENDS IlmBase ZLIB
    GIT_REPOSITORY https://github.com/AcademySoftwareFoundation/openexr
    GIT_TAG v2.5.1
    SOURCE_SUBDIR OpenEXR
    CMAKE_ARGS ${OpenEXR_ARGS})

