include(ExternalProject)

set(ILMBASE_RUNTIME_DIR lib)
if(WIN32)
    set(ILMBASE_RUNTIME_DIR bin)
endif()
set(IlmBase_ARGS
    -DCMAKE_MODULE_PATH=${CMAKE_MODULE_PATH}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_PREFIX_PATH=${CMAKE_INSTALL_PREFIX}
    -DCMAKE_C_FLAGS=${CMAKE_C_FLAGS}
    -DCMAKE_CXX_FLAGS=${CMAKE_CXX_FLAGS}
    -DCMAKE_CXX_STANDARD=11
    -DBUILD_SHARED_LIBS=${ILMBASE_SHARED_LIBS}
    -DBUILD_TESTING=OFF
    -DRUNTIME_DIR=${ILMBASE_RUNTIME_DIR})
ExternalProject_Add(
    IlmBase
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/IlmBase
    GIT_REPOSITORY https://github.com/AcademySoftwareFoundation/openexr
    GIT_TAG v2.5.1
    SOURCE_SUBDIR IlmBase
    CMAKE_ARGS ${IlmBase_ARGS})

